/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-08-26 05:41:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Header.jsp", Long.valueOf(1409030702116L));
    _jspx_dependants.put("/Footer.jsp", Long.valueOf(1409030702110L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.json-2.4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/Login.js\" charset=\"UTF-8\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Task.css\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<title>ログイン画面</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Task.css\" type=\"text/css\" />\r\n");
      out.write("<title>雇用サービス受付</title>\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id =\"header\">\r\n");
      out.write("\t\t雇用サービス受付<br />\r\n");
      out.write("\t\t");

			String userName = (String)session.getAttribute("userName");
		if (userName != null) { 
      out.write("\r\n");
      out.write("\t\t<div id=\"login\">ログイン　：");
      out.print(userName );
      out.write("</div>\r\n");
      out.write("\t\t<div id=\"logout\"><a href=\"Logout\" style=\"text-decoration: none\">ログアウト</a></div>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("\t");
 String errMsg = (String)request.getAttribute("errMsg");
		if (errMsg!=null) { 
      out.write("\r\n");
      out.write("\t\t<div id=\"errMsg\">");
      out.print(errMsg);
      out.write("</div><br />\r\n");
      out.write("\t");
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table border=\"0\" align=\"center\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<th>ユーザ</th>\r\n");
      out.write("\t\t<td><input type='text' id=\"userName\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<th>パスワード</th>\r\n");
      out.write("\t\t<td><input type='password' id=\"passward\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr><th></th><td><input type='button' style=\"width:80px;height:30px\" id=\"login\" value='ログイン'></td>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Task.css\" type=\"text/css\" />\r\n");
      out.write("<title>雇用サービス受付</title>\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"footerLeft\">\r\n");
      out.write("\t\t<a href=\"HelpPage.jsp\" style=\"text-decoration: none\">ヘルプ</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"footerRight\">\r\n");
      out.write("\t\t<a href=\"InquiryPage.jsp\" style=\"text-decoration: none\">お問い合わせ</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
